//Non volatile config
//Changed settings will be written to / loaded from a file called nvconfig.cfg
//If a nonvolatile setting is changed it is saved to that file immediately

#define MAX_NVCONFIG_SIZE 2048*128

#define NV_ConfigInit NV_LoadConfig
#define NV_ProcessBegin NV_LoadConfig
#define NV_ProcessEnd NV_WriteConfig

/*
================
NV_ClearAdminList
================
*/
void NV_ClearAdminList(){

    adminPower_t *admin, **this;

    for ( this = &svse.adminPower, admin = *this; admin ; admin = *this ){
        *this = admin->next;
        Z_Free(admin);
    }
}

/*
================
NV_ParseConfigLine
================
*/

qboolean NV_ParseConfigLine(char* line){

    adminPower_t *admin;
    int uid, power;
    const char* cmdname;

    if(!Q_stricmp(Info_ValueForKey(line, "type") , "cmdMinPower")){

        power = atoi(Info_ValueForKey(line, "power"));
        cmdname = Info_ValueForKey(line, "cmd");
        return SV_RemoteCmdSetPower(cmdname, power);

    }else if(!Q_stricmp(Info_ValueForKey(line, "type") , "admin")){

        uid = atoi(Info_ValueForKey(line, "uid"));
        power = atoi(Info_ValueForKey(line, "power"));
        if(uid < 1 || power < 1)
            return qfalse;

        admin = Z_Malloc(sizeof(adminPower_t));
        if(admin){
            admin->uid = uid;
            admin->power = power;
            admin->next = svse.adminPower;
            svse.adminPower = admin;
            return qtrue;

        }else{
            return qfalse;
        }

    }else{
        return qfalse;
    }
}


/*
================
NV_LoadConfig
================
*/

void NV_LoadConfig(){

    if(sv_authorizemode->integer != 1)
        return;

    int read;
    int error = 0;
    char buf[256];
    *buf = 0;
    fileHandle_t file;

    NV_ClearAdminList();

    FS_SV_FOpenFileRead("nvconfig.dat", &file);
    if(!file){
        Com_DPrintf("Couldn't open nvconfig.dat for reading\n");
        return;
    }
    Com_Printf( "loading nvconfig.dat\n");
    loadconfigfiles = qtrue;

    while(qtrue){
        read = FS_ReadLine(buf,sizeof(buf),file);
        if(read == 0){
            FS_FCloseFile(file);
            loadconfigfiles = qfalse;
            Com_Printf("Loaded nvconfig.dat %i errors\n", error);
            return;
        }
        if(read == -1){
            Com_Printf("Can not read from nvconfig.dat\n");
            FS_FCloseFile(file);
            loadconfigfiles = qfalse;
            return;
        }
        if(!*buf || *buf == '/' || *buf == '\n'){
            continue;
        }
        if(!NV_ParseConfigLine(buf)){
            error++;
        }
    }
}

/*
================
NV_WriteConfig
================
*/

void NV_WriteConfig(){

    if(sv_authorizemode->integer != 1)
        return;

    char* buffer;
    char infostring[1024];
    buffer = Hunk_AllocateTempMemory(MAX_NVCONFIG_SIZE);
    if(!buffer){
        Com_Printf( "Error Updating NVConfig: Hunk_Alloc failed\n" );
        return;
    }
    Com_Memset(buffer,0,MAX_NVCONFIG_SIZE);
    Q_strcat(buffer,MAX_NVCONFIG_SIZE,"//Autogenerated non volatile config settings\n");

    Q_strcat(buffer,MAX_NVCONFIG_SIZE,"\n//Minimum power settings\n");
    cmd_function_t *cmd;
    for ( cmd = cmd_functions ; cmd ; cmd = cmd->next ){
        *infostring = 0;
        Info_SetValueForKey(infostring, "type", "cmdMinPower");
        Info_SetValueForKey(infostring, "cmd", cmd->name);
        Info_SetValueForKey(infostring, "power", va("%i",cmd->minPower));
        Q_strcat(buffer,MAX_NVCONFIG_SIZE, infostring);
        Q_strcat(buffer,MAX_NVCONFIG_SIZE, "\\\n");
    }

    adminPower_t *admin;
    Q_strcat(buffer,MAX_NVCONFIG_SIZE,"\n//Admins | Users power settings\n");
    for ( admin = svse.adminPower ; admin ; admin = admin->next ){
        *infostring = 0;
        Info_SetValueForKey(infostring, "type", "admin");
        Info_SetValueForKey(infostring, "uid", va("%i",admin->uid));
        Info_SetValueForKey(infostring, "power", va("%i",admin->power));
        Q_strcat(buffer,MAX_NVCONFIG_SIZE, infostring);
        Q_strcat(buffer,MAX_NVCONFIG_SIZE, "\\\n");
    }

    FS_SV_WriteFile("nvconfig.dat",buffer,strlen(buffer));
    Hunk_FreeTempMemory(buffer);
    Com_DPrintf("NV-Config Updated\n");
}


