// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_complete_mp_spetsnaz_boris");
	self setViewmodel("viewmodel_base_viewhands");
	self.voice = "american";
}

precache()
{
	precacheModel("body_complete_mp_spetsnaz_boris");
	precacheModel("viewmodel_base_viewhands");
}